### ISSUE TITLE
Muchos "estamos"

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_covi#3]
En contacto se repite "Estamos", redactar correctamente las referencias.

**Comment by RoyArgaez** [comment]
Solo aparece 2 veces _"Estamos"_

![asslomdefyhe3rsabmk8eqeocpyvsa08ltzh-tuheckd](https://cloud.githubusercontent.com/assets/4944467/6714684/9e559196-cd67-11e4-8a5e-a55aaffb97e5.jpg)
